Issue-1905: Remove version on Nuget-related env variables
strongbox/ci-build-images pull request #21
Opened 2020-10-09 16:17 UTC by j4ckofalltrades

Necessary to allow for different major versions to be used without the
needing of code changes.

Refs #1905

# Pull Request Description

This pull request closes strongbox/strongbox#1905

# Acceptance Test

* [x] Running `./build.sh` successfully builds all images.

# Questions

* Does this pull request somehow break backward compatibility? 
  * [ ] Yes, it will require fixing build jobs.
  * [ ] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [ ] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [ ] No

2020-10-09 16:41 UTC, j4ckofalltrades commented
This will break the nuget tests in strongbox-web-integration-tests.

2020-10-10 16:19 UTC, steve-todorov requested changes
You have forgotten to apply the same changes for the `nuget3.4` images, but otherwise LGTM. :)

2020-10-10 16:33 UTC, j4ckofalltrades commented
Updated, thanks.

2020-10-10 19:27 UTC, steve-todorov approved these changes
LGMT! Thanks for fixing this! :)

2020-10-10 19:27 UTC, merged